source :rubygems

gem "rails", "2.3.11"
gem "infopark_rails_connector"
gem "infopark_ses", :path => ".."
gem "sqlite3"
gem "mysql"
gem "mysql_blob_streaming", "1.1.1"

group :test do
  gem "rspec", "~> 1.3.0"
  gem "rspec-rails", "~> 1.3.0"
  gem "prawn" # test indexing of PDFs (made on the fly)
end
