#!/usr/bin/env ruby

require 'rubygems'
require 'daemon-spawn'
require 'fileutils'

WD = File.dirname(File.dirname(__FILE__))
FileUtils.mkdir_p "#{WD}/log"
FileUtils.mkdir_p "#{WD}/tmp/pids"

class Ses < DaemonSpawn::Base
  def start(args)
    exec "#{WD}/script/runner ::Infopark::SES::Indexer.serve"
  end

  def stop
  end
end

Ses.spawn!(:working_dir => WD,
    :log_file => "#{WD}/log/ses.log",
    :pid_file => "#{WD}/tmp/pids/ses.pid")
