#!/usr/bin/env ruby

require File.expand_path('../../config/environment',  __FILE__)

require 'daemon_spawn'

puts "SES Indexer is using #{Rails.env} environment"

class Ses < DaemonSpawn::Base

  def start(args)
    ::Infopark::SES::Indexer.serve
  end

  def stop
  end

end

Ses.spawn!(:working_dir => Rails.root,
    :application => 'SES Indexer',
    :log_file => "#{Rails.root}/log/ses-indexer.log",
    :pid_file => "#{Rails.root}/tmp/pids/ses-indexer.pid",
    :singleton => true)
